### ISSUE TITLE
Please add more info

### ISSUE THREAD

**Issue by thermatk** [ashkitten/g933-utils#1]
Hi!
There is no info how to compile and use it properly yet

I've installed nightly rustc and did the ordinary `cargo build`, but it doesn't start anyway, so I guess I do something wrong 😊

**Comment by ashkitten** [comment]
Hi! Thanks for your interest in my project! I'll add that to the readme soon, but for now you can run it like `g933-utils get <property>` or `g933-utils set <property> <data>`

valid properties for `get` are currently:
- `battery`

valid properties for `set` are currently:
- `report_buttons`
- `sidetone_volume`

There is a `raw` subcommand if you would like to send raw packets and read the response (useful for quick testing). The format for this is `g933-utils raw <bytes>` where `<bytes>` is a space separated list of hex bytes (without the 0x prefix)

I hope this helps!

**Comment by thermatk** [comment]
so I tried again:

```
git clone https://github.com/ashkitten/g933-utils.git
cd g933-utils
cargo build
cd target/debug
./g933 list
```

shows nothing, also tried with sudo
When tried just `get battery`, it returns:

```
thread 'main' panicked at 'assertion failed: index < len', liballoc/vec.rs:772:9
note: Run with RUST_BACKTRACE=1 for a backtrace
```
do I need to load a specific kernel module? My device is the `Bus 001 Device 009: ID 046d:0a5b Logitech, Inc. G933 Wireless Headset Dongle`

**Comment by ashkitten** [comment]
hmm it should work, as long as you have udev and the kernel supports hidraw. can you run with `RUST_BACKTRACE=1`?

**Comment by thermatk** [comment]
For `RUST_BACKTRACE=1 ./g933-utils get battery`
```
thread 'main' panicked at 'assertion failed: index < len', liballoc/vec.rs:772:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::panicking::panic
             at libcore/panicking.rs:51
  10: <alloc::vec::Vec<T>>::remove
             at /tmp/g933-utils/<panic macros>:3
  11: g933_utils::run
             at src/main.rs:61
  12: g933_utils::main
             at src/main.rs:129
  13: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  14: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  15: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  16: std::rt::lang_start_internal
             at libstd/panicking.rs:458
             at libstd/panic.rs:358
             at libstd/rt.rs:58
  17: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  18: main
  19: __libc_start_main
  20: _start
```
But I think the problem is one level up, the `list` command silently shows nothing, so no device found.

Here is the line from kernel log, for some reason with another id? 
```
[  553.738358] hid-generic 0003:046D:0A5D.0005: hiddev1,hidraw4: USB HID v1.11 Device [Logitech G933 Artemis Spectrum Snow Battery Charger] on usb-0000:00:14.0-2/input0
```

And full `lsusb -v` is attached
[lsusb-v.txt](https://github.com/ashkitten/g933-utils/files/1680715/lsusb-v.txt)

**Comment by ashkitten** [comment]
ahhhhhh, you have the Snow variant. Change any instances of `0a5b` to `0a5d` and see if it works then. I'll add support to the tool in a bit.

**Comment by ashkitten** [comment]
That might not work, though, since the dongle shows up as `0a5b`. Was just a guess.

**Comment by ashkitten** [comment]
hmm, that probably won't work, thinking about it. I'm not really sure why it's not finding your headset properly. can I get some more system information?

**Comment by ashkitten** [comment]
Ahhh I totally forgot to add udev rules to the repository, so that might be it! Can you add this rule as `/etc/udev/rules.d/90-logitech.rules`?:

```
SUBSYSTEM=="usb", ATTRS{idVendor}=="046d", GROUP="logitech"
SUBSYSTEM=="hidraw", ATTRS{idVendor}=="046d", GROUP="logitech"
```

Then add yourself to the `logitech` group and log out and back in.

**Comment by thermatk** [comment]
added udev rules, restarted, pulled latest changes, built
all the same
would you consider adding some debug output, maybe list all the devices the app can see at all? 😄

**Comment by ashkitten** [comment]
I'll add more debug output for the enumeration process. Try running with `RUST_LOG=libg933=debug` this time.

**Comment by thermatk** [comment]
`INFO:libg933: Found usb device: 1-3`

**Comment by ashkitten** [comment]
And there is no hidraw device node found?

**Comment by thermatk** [comment]
That's the only output it gives

I also have G502 from Logitech, just in case it matters, they are on hidraw2 and 3. G933 is hidraw4 currently
Your udev rules being so general affect the G502 as well, but functionality didn't change.
The hidraw2, 3 and 4 all belong to `logitech` group now and I'm in it

**Comment by ashkitten** [comment]
Okay. Did you revert the changes I mistakenly suggested about the product ID?

**Comment by thermatk** [comment]
I clone from scratch everytime, just in case

**Comment by ashkitten** [comment]
Alright. Can you give the output of `udevadm info -n $HIDRAW_DEVNODE -a` please? $HIDRAW_DEVNODE should be the full path of the hidraw device node given in the kernel log.

**Comment by thermatk** [comment]
i figured out something - the 0A5D is the hidraw device I get when attaching the charging cable. 
Which one do we need here?

**Comment by ashkitten** [comment]
You need the dongle device.

**Comment by thermatk** [comment]
Ok, that must be the issue
I can't get a hidraw from the dongle actually. I've found some pastebins on google, so I know how it should look, but mine doesn't get a hidraw device recognized reliably. 
I've seen it a couple of times, but can't reproduce anymore. The hidraw device is there when using the on-headset volume button affects the system volume level, otherwise it affects some internal level and beeps. My guess would be that it also has to do with latest kernel updates, because last week I saw hidraw a lot more

**Comment by ashkitten** [comment]
Did you add the quirks parameter from the hobo.house article? That adds the flag `HID_QUIRK_IGNORE`, which prevents binding to the usbhid driver. Remove that parameter.

**Comment by thermatk** [comment]
Removed the quirks, restarted, not there. Here is the journalctl output after attaching, no sign of hidraw:
```
янв 31 23:42:47 thermatk-desk kernel: usb 1-3: new full-speed USB device number 6 using xhci_hcd
янв 31 23:42:48 thermatk-desk mtp-probe[2171]: checking bus 1, device 6: "/sys/devices/pci0000:00/0000:00:14.0/usb1/1-3"
янв 31 23:42:48 thermatk-desk mtp-probe[2171]: bus: 1, device: 6 was not an MTP device
янв 31 23:42:48 thermatk-desk upowerd[804]: unhandled action 'bind' on /sys/devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.2
янв 31 23:42:48 thermatk-desk upowerd[804]: unhandled action 'bind' on /sys/devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.1
янв 31 23:42:48 thermatk-desk upowerd[804]: unhandled action 'bind' on /sys/devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.0
янв 31 23:42:48 thermatk-desk upowerd[804]: unhandled action 'bind' on /sys/devices/pci0000:00/0000:00:14.0/usb1/1-3
янв 31 23:42:48 thermatk-desk rtkit-daemon[831]: Supervising 2 threads of 1 processes of 1 users.
янв 31 23:42:48 thermatk-desk rtkit-daemon[831]: Successfully made thread 2194 of process 830 (/usr/bin/pulseaudio) owned by '1000' RT at priority 5.
янв 31 23:42:48 thermatk-desk rtkit-daemon[831]: Supervising 3 threads of 1 processes of 1 users.
янв 31 23:42:48 thermatk-desk rtkit-daemon[831]: Supervising 3 threads of 1 processes of 1 users.
янв 31 23:42:48 thermatk-desk rtkit-daemon[831]: Successfully made thread 2195 of process 830 (/usr/bin/pulseaudio) owned by '1000' RT at priority 5.
янв 31 23:42:48 thermatk-desk rtkit-daemon[831]: Supervising 4 threads of 1 processes of 1 users.
янв 31 23:42:48 thermatk-desk gsd-media-keys[996]: Unable to get default sink
янв 31 23:42:48 thermatk-desk gnome-shell[789]: Removed: 18
янв 31 23:42:48 thermatk-desk gnome-shell[789]: Цифровой выход (S/PDIF)
                                                   (G933 Wireless Headset Dongle)
янв 31 23:42:48 thermatk-desk gnome-shell[789]: Added: 19:Цифровой выход (S/PDIF):iec958-stereo-output
янв 31 23:42:48 thermatk-desk gnome-shell[789]: Аналоговый выход
                                                   (G933 Wireless Headset Dongle)
янв 31 23:42:48 thermatk-desk gnome-shell[789]: Added: 20:Аналоговый выход:analog-output
янв 31 23:42:48 thermatk-desk gnome-shell[789]: Микрофон
                                                   (G933 Wireless Headset Dongle)
янв 31 23:42:48 thermatk-desk gnome-shell[789]: Added: 21:Микрофон:analog-input-mic
янв 31 23:42:48 thermatk-desk gnome-shell[789]: Activated: 19
```

**Comment by thermatk** [comment]
As suggested online to determine the kernel module in use, I ran `usb-devices`
here is the output:
```
T:  Bus=01 Lev=01 Prnt=01 Port=02 Cnt=01 Dev#=  6 Spd=12  MxCh= 0
D:  Ver= 1.10 Cls=00(>ifc ) Sub=00 Prot=00 MxPS=64 #Cfgs=  1
P:  Vendor=046d ProdID=0a5b Rev=01.01
S:  Manufacturer=Logitech
S:  Product=G933 Artemis Spectrum Snow
C:  #Ifs= 4 Cfg#= 1 Atr=80 MxPwr=100mA
I:  If#=0x0 Alt= 0 #EPs= 0 Cls=01(audio) Sub=01 Prot=00 Driver=snd-usb-audio
I:  If#=0x1 Alt= 0 #EPs= 0 Cls=01(audio) Sub=02 Prot=00 Driver=snd-usb-audio
I:  If#=0x2 Alt= 2 #EPs= 1 Cls=01(audio) Sub=02 Prot=00 Driver=snd-usb-audio
I:  If#=0x3 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=00 Prot=00 Driver=(none)
```

As expected there is no driver attached, but I have no idea why. Didn't ever touch anything in usb subsystem except for quirks from the article

**Comment by ashkitten** [comment]
What is the output of `sudo cat /sys/kernel/debug/usb/devices`?

**Comment by ashkitten** [comment]
Oh I didn't see the usb-devices output

**Comment by ashkitten** [comment]
It seems that it doesn't have any driver attached to it. What is the output of `cat /sys/module/usbhid/parameters/quirks`, to make sure that it is actually not applying module load time quirks?

**Comment by thermatk** [comment]
Booted into kernel 4.14, hidraw came up and everything works now, probably 4.15 is not as ready as it should be
hooray!
```
BatteryStatus { charging_status: Discharging, voltage: 3816, charge: 100.0 }
```
I'm pretty certain it's not 100% though, couple of hours discharging already 😄

**Comment by thermatk** [comment]
Thank you, the `set` commands work as well!
Incredibly cool project 👍 
case resolved

**Comment by ashkitten** [comment]
:+1:

**Comment by ashkitten** [comment]
@thermatk Looks like I made a simple mistake in clamping the charge between 0 and 100, should be fixed now.
