### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by AllOgreTheWorld** [ashkitten/g933-utils#12]
I am receiving an issue when running cargo build --release, here is what I see on my end:

Compiling proc-macro2 v0.4.28                                                
   Compiling unicode-xid v0.1.0                                                 
   Compiling syn v0.15.32                                                       
   Compiling libc v0.2.51                                                       
   Compiling cc v1.0.35                                                         
   Compiling pkg-config v0.3.14                                                 
   Compiling memchr v2.2.0                                                      
   Compiling autocfg v0.1.2                                                     
   Compiling failure_derive v0.1.5                                              
   Compiling rustc-demangle v0.1.14                                             
   Compiling regex v0.2.11                                                      
   Compiling proc-macro-hack-impl v0.4.1                                        
   Compiling cfg-if v0.1.7                                                      
   Compiling byteorder v1.3.1                                                   
   Compiling lazy_static v1.3.0                                                 
   Compiling ucd-util v0.1.3                                                    
   Compiling unicode-width v0.1.5                                               
   Compiling unindent v0.1.3                                                    
   Compiling utf8-ranges v1.0.2                                                 
   Compiling bitflags v1.0.4                                                    
   Compiling strsim v0.8.0                                                      
   Compiling vec_map v0.8.1                                                     
   Compiling ansi_term v0.11.0                                                  
   Compiling log v0.4.6                                                         
   Compiling thread_local v0.3.6                                                
   Compiling textwrap v0.11.0                                                   
   Compiling regex-syntax v0.5.6                                                
   Compiling backtrace v0.3.15                                                  
   Compiling log v0.3.9                                                         
   Compiling libudev-sys v0.1.4                                                 
   Compiling proc-macro-hack v0.4.1                                             
   Compiling aho-corasick v0.6.10                                               
error: failed to run custom build command for `libudev-sys v0.1.4`              
process didn't exit successfully: `/home/user/Downloads/g933-utils/target/release/build/libudev-sys-b7a3adae5ce368e7/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"libudev\"` did not exit successfully: exit code: 1\n--- stderr\nPackage libudev was not found in the pkg-config search path.\nPerhaps you should add the directory containing `libudev.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'libudev\' found\n"', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by ashkitten** [comment]
what operating system is this? g933-utils currently only supports linux

**Comment by AllOgreTheWorld** [comment]
OS is Linux Mint 19.1 Tessa
libudev is installed at version 237-3ubuntu10.21

**Comment by AllOgreTheWorld** [comment]
Nevermind, I got it working. The package libudev-dev needed to be installed as well.
