### ISSUE TITLE
possibility to detect wheter the headset is connected or not

### ISSUE THREAD

**Issue by mgolisch** [ashkitten/g933-utils#5]
it seems all set commands hang forever if the a dongle is found but the headset is turned off.

**Comment by mgolisch** [comment]
or rather every command that talks to the headset

**Comment by ashkitten** [comment]
I'm not entirely sure how to implement this, since sometimes commands will not get addressed by the headset and need to be re-sent. I could maybe change it so that it will only re-send the command a certain number of times before returning an error? Does anyone have any thoughts on this?

**Comment by mgolisch** [comment]
sorry, i have no idea about the communitcation protocol between the dongle and the headset and wheter its able to somehow detect or report if one is connected.
I think i can help myself out of now using the timeout command.
basicaly iam calling g933-utils get battery to show the remaining battery and display it in my i3 status bar, wheverver the headset is the default pulseaudio device.

**Comment by mgolisch** [comment]
still would be cool for the commands either to fail or have a dedicated command to detect wheter a headset is connected or not

**Comment by ashkitten** [comment]
fixed with 27d3239

**Comment by mgolisch** [comment]
lovely! keep up the great work.
